module_separator = " "
reset_color = true

[bookmarks]
search_depth = 100
exclude = []

[[module]]
type = "Symbol"
symbol = "󰘬"
color = "BrightBlack"

[[module]]
type = "Bookmarks"
separator = " "
color = "BrightBlack"
behind_symbol = "↑"
surround_with_quotes = false

[[module]]
type = "Commit"
max_length = 24
empty_text = ""
surround_with_quotes = false
color = "BrightBlack"

[[module]]
type = "State"
separator = " "

[module.conflict]
disabled = false
text = "(conflict)"
color = "Red"

[module.divergent]
disabled = false
text = "(divergent)"
color = "Cyan"

[module.empty]
disabled = true
text = "∅"
color = "Yellow"

[module.immutable]
disabled = false
text = "(immutable)"
color = "Yellow"

[module.hidden]
disabled = false
text = "(hidden)"
color = "Yellow"

[[module]]
type = "Metrics"
# template = "[{changed} {added}{removed}]"
template = "{changed}"
color = "Yellow"

[module.changed_files]
# prefix = "󰇂 "
prefix = " "
suffix = ""
color = "Yellow"

[module.added_lines]
prefix = "+"
suffix = ""
color = "BrightBlack"

[module.removed_lines]
prefix = "-"
suffix = ""
color = "BrightBlack"
